version: '3.1'
services:
  backend:
    build: ./backend
    container_name: digital_preservation_backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    container_name: digital_preservation_frontend
    ports:
      - "4200:4200"